env: "local"
database:
  driver: "postgres"
  host: "postgres"
  port: 5432
  user: "admin"
  password: "admin"
  dbname: "sso_db"
  selmode: "disable"
  
grpc:
  port: 44044
  timeout: 10h

migrations_path: "./migrations"
token_ttl: 24h


